<a href="https://colab.research.google.com/github/maggieliuzzi/numpy_matplotlib_pandas_scipy/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

**Numpy Arrays**

In [53]:
np.random.randn(10)  # type: numpy.ndarray

array([-0.77368352,  0.70659765,  0.31812008,  0.01628257,  1.77377952,
        0.16904545,  0.01168565, -1.47649196, -0.12047315, -0.28133481])

In [0]:
L = [1,2,3]
A = np.array([1,2,3])

**Vector Operations**

In [2]:
L + [4]

[1, 2, 3, 4]

In [7]:
A + [4]  # same as doing:  A + np.array(4) OR A + np.array([4])

array([5, 6, 7])

In [10]:
A + [4,5,6]  # A + np.array([4,5,6])

array([5, 7, 9])

In [0]:
2 * A  # whereas: 2 * L: [1, 2, 3, 1, 2, 3]
2.5 * A

array([2.5, 5. , 7.5])

In [19]:
A ** 2
np.sqrt(A)

array([1, 4, 9])

**Functions** (element-wise)

In [21]:
np.log(A)
np.exp(A)

array([0.        , 0.69314718, 1.09861229])

In [23]:
np.tanh(A)  # hyperbolic tangent

array([0.76159416, 0.96402758, 0.99505475])

In [25]:
np.sin(A)
np.cos(A)

array([ 0.54030231, -0.41614684, -0.9899925 ])

**Dot Products**

In [45]:
a = np.array([1, 2])
b = np.array([3, 4])
np.dot(a, b)  # np.sum(a*b)  # (a*b).sum
a.dot(b)  # a must be numpy array
a @ np.array(b)  # a and b must be np arrays  

# aT b = ||a|| ||b|| cos(theta a,b)
# ||a||: amag
mag_a = np.linalg.norm(a)  # np.sqrt((a**2).sum())
mag_b = np.linalg.norm(b)
cosangle = a.dot(b) / (mag_a * mag_b)  # aT b // ||a|| ||b||  # cosine of angle
angle = np.arccos(cosangle)  # arc cosine
angle

0.17985349979247847

**Matrices**

In [48]:
M = np.array([[1,2],[3,4]])
M

array([[1, 2],
       [3, 4]])

In [90]:
np.diag(A)  # diagonal matrix from a vector

array([[1, 0],
       [0, 2]])

In [58]:
M[1]  # row 1

array([3, 4])

In [59]:
M[0,1]  # M[0][1]  # Element in row 0 column 1

2

In [60]:
M[:,0]  # column 0
M[:,1]  # column 1
# : selects everything in a dimension

array([2, 4])

In [81]:
np.diag(M)

array([1, 4])

**Functions** (element-wise)

In [62]:
np.exp(M)  # M can be a normal list

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

**Matrix Operations**

In [61]:
M.T  # transpose

array([[1, 3],
       [2, 4]])

In [86]:
N = np.array([[1,2,3],[4,5,6]])  # np.diag(N) is [1,5]
N

array([[1, 2, 3],
       [4, 5, 6]])

In [70]:
M.dot(N)

array([[ 9, 12, 15],
       [19, 26, 33]])

In [79]:
np.linalg.det(M)  # not exactly accurate in a computer

-2.0000000000000004

In [76]:
inv_M = np.linalg.inv(M)
inv_M

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [78]:
inv_M.dot(M)  # inaccurate operation in a computer

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

In [80]:
np.trace(M)

5

In [0]:
lam, V = np.linalg.eig(M)  # Eigenvalues and Eigenvectors  # Eigenvectors are stored as column vectors inside V

In [109]:
V[:,0] * lam[0] == M @ V[:,0]  # eigenvalue * eigenvector == A * eigenvector  # incorrect due to numerical precision errors
V[:,0] * lam[0], M @ V[:,0]  # (array([ 0.30697009, -0.21062466]), array([ 0.30697009, -0.21062466]))
np.allclose(V[:,0] * lam[0], M @ V[:,0])
np.allclose(V @ np.diag(lam), M @ V)  # checking all eigenvectors simultaneously
# if matrix is symmetric (eg.covariance) (or complex Hermitian), use np.linalg.eigh 
# (Hermitian: complex analog of matrix transpose: it does a transpose and takes the complex conjugates of the elements

True